version: '4'
services:
  jekyll:
    image: 'jekyll/jekyll:3.8'
    volumes:
      - "$PWD:/srv/jekyll"
    ports:
      - '4000:4000'
      - '8080:8080'
    command: jekyll serve --incremental
    tty: true
