<<<<<<< HEAD
version: '6'
=======
version: '1'
>>>>>>> 92ce555a677e35077575565b0d8930fbd623e42d
services:
  jekyll:
    image: 'jekyll/jekyll:3.8'
    volumes:
      - "$PWD:/srv/jekyll"
    ports:
      - '4000:4000'
      - '8080:8080'
    command: jekyll serve --incremental
    tty: true
